
spring:
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/woorder?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: luffy
    password: 1234

logging:
  level:
    root: INFO
